# Generated by Django 5.2.4 on 2025-09-11 23:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name="userprofile",
            name="tags",
        ),
        migrations.AddField(
            model_name="userprofile",
            name="last_5_solved_pids",
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="user",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="recommender_profile",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
