# Generated by Django 5.2.4 on 2025-08-18 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("problem", "0003_remove_problem_examples_remove_problem_hints"),
    ]

    operations = [
        migrations.CreateModel(
            name="Tag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.RemoveField(
            model_name="problem",
            name="tags",
        ),
        migrations.AddField(
            model_name="problem",
            name="tags",
            field=models.ManyToManyField(
                blank=True, related_name="problems", to="problem.tag"
            ),
        ),
    ]
