# Generated by Django 5.2.4 on 2025-09-11 22:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("problem", "0004_tag_remove_problem_tags_problem_tags"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="problem",
            name="embedding",
            field=models.BinaryField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="problem",
            name="creator",
            field=models.ForeignKey(
                default="leo",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="created_problems",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
